// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sjsu.movie.domain;

import com.sjsu.movie.domain.MemberTypeDataOnDemand;
import com.sjsu.movie.domain.MembershipInfo;
import com.sjsu.movie.domain.MembershipInfoDataOnDemand;
import com.sjsu.movie.domain.MovieUserDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect MembershipInfoDataOnDemand_Roo_DataOnDemand {
    
    declare @type: MembershipInfoDataOnDemand: @Component;
    
    private Random MembershipInfoDataOnDemand.rnd = new SecureRandom();
    
    private List<MembershipInfo> MembershipInfoDataOnDemand.data;
    
    @Autowired
    MemberTypeDataOnDemand MembershipInfoDataOnDemand.memberTypeDataOnDemand;
    
    @Autowired
    MovieUserDataOnDemand MembershipInfoDataOnDemand.movieUserDataOnDemand;
    
    public MembershipInfo MembershipInfoDataOnDemand.getNewTransientMembershipInfo(int index) {
        MembershipInfo obj = new MembershipInfo();
        setBalance(obj, index);
        setCreatedDate(obj, index);
        setMembershipId(obj, index);
        setMembershipNumber(obj, index);
        setOutstandingMovies(obj, index);
        setUpdatedDate(obj, index);
        setUserId(obj, index);
        return obj;
    }
    
    public void MembershipInfoDataOnDemand.setBalance(MembershipInfo obj, int index) {
        Double balance = new Integer(index).doubleValue();
        obj.setBalance(balance);
    }
    
    public void MembershipInfoDataOnDemand.setCreatedDate(MembershipInfo obj, int index) {
        Date createdDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setCreatedDate(createdDate);
    }
    
    public void MembershipInfoDataOnDemand.setMembershipId(MembershipInfo obj, int index) {
        Integer membershipId = new Integer(index);
        obj.setMembershipId(membershipId);
    }
    
    public void MembershipInfoDataOnDemand.setMembershipNumber(MembershipInfo obj, int index) {
        String membershipNumber = "membershipNumber_" + index;
        obj.setMembershipNumber(membershipNumber);
    }
    
    public void MembershipInfoDataOnDemand.setOutstandingMovies(MembershipInfo obj, int index) {
        Integer outstandingMovies = new Integer(index);
        obj.setOutstandingMovies(outstandingMovies);
    }
    
    public void MembershipInfoDataOnDemand.setUpdatedDate(MembershipInfo obj, int index) {
        Date updatedDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setUpdatedDate(updatedDate);
    }
    
    public void MembershipInfoDataOnDemand.setUserId(MembershipInfo obj, int index) {
        Integer userId = new Integer(index);
        obj.setUserId(userId);
    }
    
    public MembershipInfo MembershipInfoDataOnDemand.getSpecificMembershipInfo(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        MembershipInfo obj = data.get(index);
        Long id = obj.getId();
        return MembershipInfo.findMembershipInfo(id);
    }
    
    public MembershipInfo MembershipInfoDataOnDemand.getRandomMembershipInfo() {
        init();
        MembershipInfo obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return MembershipInfo.findMembershipInfo(id);
    }
    
    public boolean MembershipInfoDataOnDemand.modifyMembershipInfo(MembershipInfo obj) {
        return false;
    }
    
    public void MembershipInfoDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = MembershipInfo.findMembershipInfoEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'MembershipInfo' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<MembershipInfo>();
        for (int i = 0; i < 10; i++) {
            MembershipInfo obj = getNewTransientMembershipInfo(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
